app-config:
  llm: 'mistralai/Mixtral-8x7B-Instruct-v0.1'
  huggingface-hub-token: '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'
  prompt_path: 'prompts/'
  log_prompts: false
  log_llm_responses: true
  show_sentence: true